### ISSUE TITLE
Edit own Researcher Profile Page: Authorization required

### ISSUE THREAD

**Issue by andrelanger** [4Science/DSpace#121]
We have deployed branch dspace-6.x.x-cris in a Linux Mint (Ubuntu)  and done a fresh install.

DSpace version:  CRIS-6.3.0-SNAPSHOT
OS:  Linux(amd64) version 4.15.0-54-generic
JRE:  Private Build version 1.8.0_232
Ant version:  Apache Ant(TM) version 1.10.5 compiled on March 28 2019
Maven version:  3.6.0
ORCID Sandbox support enabled in local.cfg with corresponding OAuth credentials.

After registering a new user and signing on, I created a researcher page for it and clicked on "View your profile". This works fine and I can see my publication list and all the other tabs.
However, when I click on Edit Researcher Page, I get an Authorization Required message.
No further exceptions or warnings can be found in the application log.

(If I sign-on as an administrator and click on Administer -> CRIS Module -> Researcher Pages > View All Researchers -> ID, I get an exception stating

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.ClassCastException: java.lang.Integer cannot be cast to java.math.BigInteger
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:963)
[...]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.math.BigInteger
        at org.dspace.content.authority.AuthorityDAO.countIssuedItemsByAuthorityValueAndFieldId(AuthorityDAO.java:200)
        at org.dspace.content.authority.AuthorityDAO.countIssuedItemsByAuthorityValueInAuthority(AuthorityDAO.java:195)
        at org.dspace.app.webui.cris.controller.ResearcherPageDetailsController.handleDetails(ResearcherPageDetailsController.java:159)
        at it.cilea.osd.jdyna.web.controller.SimpleDynaController.handleRequestInternal(SimpleDynaController.java:116)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
[...])

What am I doing wrong?
How can I give a researcher edit rights for its own researcher page?

**Comment by andrelanger** [comment]
does not occur in latest release
