### ISSUE TITLE
file uploading fails

### ISSUE THREAD

**Issue by luda171** [4Science/DSpace#193]
branch "dspace-6_x_x-cris"
File uploading fails during the manual item insert procedure. Could you tell me what can cause it?

The  error at the dspace log:
ERROR org.dspace.event.BasicDispatcher @ Consumer("resourcesync").consume threw: java.lang.NullPointerException
java.lang.NullPointerException
	at org.apache.solr.client.solrj.impl.HttpSolrServer.<init>(HttpSolrServer.java:150)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.<init>(HttpSolrServer.java:141)
	at org.dspace.resourcesync.ResourceSyncAuditService.getSolr(ResourceSyncAuditService.java:80)
	at org.dspace.resourcesync.ResourceSyncAuditService.addEvent(ResourceSyncAuditService.java:106)
	at org.dspace.resourcesync.ResourceSyncConsumer.addEvent(ResourceSyncConsumer.java:253)
	at org.dspace.resourcesync.ResourceSyncConsumer.addUpdateEvent(ResourceSyncConsumer.java:244)
	at org.dspace.resourcesync.ResourceSyncConsumer.consumeItemEvent(ResourceSyncConsumer.java:176)
	at org.dspace.resourcesync.ResourceSyncConsumer.consume(ResourceSyncConsumer.java:77)
	at org.dspace.event.BasicDispatcher.dispatch(BasicDispatcher.java:119)
	at org.dspace.core.Context.dispatchEvents(Context.java:501)
	at org.dspace.submit.step.DescribeStep.doProcessing(DescribeStep.java:419)
	at org.dspace.app.webui.submit.JSPStepManager.doStepEnd(JSPStepManager.java:399)
	at org.dspace.app.webui.submit.JSPStepManager.processStep(JSPStepManager.java:250)
	at org.dspace.app.webui.servlet.SubmissionController.doStep(SubmissionController.java:537)
	at org.dspace.app.webui.servlet.SubmissionController.doDSPost(SubmissionController.java:475)
	at org.dspace.app.webui.servlet.DSpaceServlet.processRequest(DSpaceServlet.java:122)
	at org.dspace.app.webui.servlet.DSpaceServlet.doPost(DSpaceServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:149)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.app.webui.filter.RegisteredOnlyFilter.doFilter(RegisteredOnlyFilter.java:66)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)

**Comment by lap82** [comment]
Dear @luda171 

I think that the errors is related to your configuration of solr core. I guess that you using solr multicore https://github.com/4Science/DSpace/blob/dspace-6_x_x-cris/dspace/config/local.cfg.EXAMPLE#L67 and this is not permitted by ResourceSync module on java code. Now I added support with commit https://github.com/4Science/DSpace/commit/8b92c868b601582b3d2251d78397f79962b2bc5c, please rebuild the branch with the last commit.

Note that "ResourceSync" module is an experimental module of DSpace-CRIS and you can disable it changing on dspace.cfg the consumers list at https://github.com/4Science/DSpace/blob/dspace-6_x_x-cris/dspace/config/dspace.cfg#L731. Removiing "resourcesync" value from the list of consumers you can disable the core functionality.  

Please, let me know.
