### ISSUE TITLE
Cannot Install dspace-cris 7 on windows

### ISSUE THREAD

**Issue by s0517691** [4Science/DSpace#229]
test_database:
     [java] Failure during kernel init: Error creating bean with name 'org.dspace.importer.external.service.ImportService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]: Cannot resolve reference to bean 'grobidImportMetadataSourceService' while setting bean property 'importSources' with key [6]; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grobidImportMetadataSourceService': Unsatisfied dependency expressed through field 'grobidClient'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 2021-06-11 05:20:19,415 WARN  org.springframework.context.support.ClassPathXmlApplicationContext @ Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.importer.external.service.ImportService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]: Cannot resolve reference to bean 'grobidImportMetadataSourceService' while setting bean property 'importSources' with key [6]; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grobidImportMetadataSourceService': Unsatisfied dependency expressed through field 'grobidClient'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.importer.external.service.ImportService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]: Cannot resolve reference to bean 'grobidImportMetadataSourceService' while setting bean property 'importSources' with key [6]; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grobidImportMetadataSourceService': Unsatisfied dependency expressed through field 'grobidClient'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:428)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:173)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1699)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1444)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
     [java] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
     [java] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
     [java] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
     [java] 	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:277)
     [java] 	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:153)
     [java] 	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:128)
     [java] 	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:71)
     [java] Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grobidImportMetadataSourceService': Unsatisfied dependency expressed through field 'grobidClient'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
     [java] 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
     [java] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
     [java] 	... 18 more
     [java] Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1477)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:682)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:649)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1605)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:523)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:502)
     [java] 	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:265)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1456)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1253)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210)
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
     [java] 	... 28 more
     [java] Caused by: java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
     [java] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
     [java] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
     [java] 	at java.base/java.lang.Class.forName0(Native Method)
     [java] 	at java.base/java.lang.Class.forName(Class.java:398)
     [java] 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:285)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:456)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1542)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1469)
     [java] 	... 38 more
     [java] Exception in thread "main" java.lang.IllegalStateException: Failure during kernel init: Error creating bean with name 'org.dspace.importer.external.service.ImportService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]: Cannot resolve reference to bean 'grobidImportMetadataSourceService' while setting bean property 'importSources' with key [6]; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grobidImportMetadataSourceService': Unsatisfied dependency expressed through field 'grobidClient'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:83)
     [java] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.dspace.importer.external.service.ImportService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]: Cannot resolve reference to bean 'grobidImportMetadataSourceService' while setting bean property 'importSources' with key [6]; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grobidImportMetadataSourceService': Unsatisfied dependency expressed through field 'grobidClient'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:428)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:173)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1699)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1444)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
     [java] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
     [java] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
     [java] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
     [java] 	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:277)
     [java] 	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:153)
     [java] 	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:128)
     [java] 	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:71)
     [java] Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grobidImportMetadataSourceService': Unsatisfied dependency expressed through field 'grobidClient'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
     [java] 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
     [java] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
     [java] 	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
     [java] 	... 18 more
     [java] Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl] for bean with name 'OpenAIREService' defined in URL [jar:file:/E:/dspace-installer/lib/dspace-api-cris-2021.01.01-SNAPSHOT.jar!/spring/spring-dspace-addon-import-services.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1477)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:682)
     [java] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:649)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1605)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:523)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:502)
     [java] 	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:265)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1456)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1253)
     [java] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210)
     [java] 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
     [java] 	... 28 more
     [java] Caused by: java.lang.ClassNotFoundException: org.dspace.importer.external.openAire.service.OpenAireProjectImportMetadataSourceServiceImpl
     [java] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
     [java] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
     [java] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
     [java] 	at java.base/java.lang.Class.forName0(Native Method)
     [java] 	at java.base/java.lang.Class.forName(Class.java:398)
     [java] 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:285)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:456)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1542)
     [java] 	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1469)
     [java] 	... 38 more

**Comment by STORMSQ** [comment]
same problem

Did you found solution?
