### ISSUE TITLE
Can't able to create administrator account

### ISSUE THREAD

**Issue by AjitLibrary** [4Science/DSpace#251]
/C/dspace/bin/dspace create-administrator
Exception: Flyway migration error occurred
java.lang.IllegalStateException: Flyway migration error occurred
        at org.dspace.storage.rdbms.DatabaseManager.getDataSource(DatabaseManager.java:729)
        at org.dspace.storage.rdbms.DatabaseManager.getConnection(DatabaseManager.java:703)
        at org.dspace.core.Context.init(Context.java:155)
        at org.dspace.core.Context.<init>(Context.java:129)
        at org.dspace.administer.CreateAdministrator.<init>(CreateAdministrator.java:97)
        at org.dspace.administer.CreateAdministrator.main(CreateAdministrator.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
        at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)
Caused by: java.sql.SQLException: Flyway migration error occurred
        at org.dspace.storage.rdbms.DatabaseUtils.updateDatabase(DatabaseUtils.java:493)
        at org.dspace.storage.rdbms.DatabaseUtils.updateDatabase(DatabaseUtils.java:400)
        at org.dspace.storage.rdbms.DatabaseManager.initialize(DatabaseManager.java:1473)
        at org.dspace.storage.rdbms.DatabaseManager.getDataSource(DatabaseManager.java:724)
        ... 11 more
Caused by: org.flywaydb.core.api.FlywayException: Error while retrieving the list of applied migrations from metadata table "public"."schema_version"
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.findAppliedMigrations(MetaDataTableImpl.java:256)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.allAppliedMigrations(MetaDataTableImpl.java:190)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:97)
        at org.flywaydb.core.Flyway$4.execute(Flyway.java:953)
        at org.flywaydb.core.Flyway$4.execute(Flyway.java:942)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1171)
        at org.flywaydb.core.Flyway.info(Flyway.java:942)
        at org.dspace.storage.rdbms.DatabaseUtils.updateDatabase(DatabaseUtils.java:469)
        ... 14 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "version_rank" does not exist
  Position: 8
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254)
        at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
        at org.flywaydb.core.internal.dbsupport.JdbcTemplate.query(JdbcTemplate.java:304)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.findAppliedMigrations(MetaDataTableImpl.java:233)
        ... 21 more

**Comment by AjitLibrary** [comment]
Can anyone help me to solve this problem
