### ISSUE TITLE
Internal Error on Update status (authors, organizations)

### ISSUE THREAD

**Issue by josekarvalho** [4Science/DSpace#5]
When changing the status of a entity (RPs and OrgUnit at least) there is an internal error when saving. 

This has been tested on the Demo DSpaceCRIS instance with the same consequence.

The log is here:

-- list[37].status: "true"
-- list[44].status: "true"

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [org.dspace.app.cris.model.ResearcherPage#2]
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:894)
                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                at org.dspace.app.webui.cris.filter.DSpaceContextCleanupFilter.doFilter(DSpaceContextCleanupFilter.java:54)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                at org.dspace.app.webui.filter.AdminOnlyFilter.doFilter(AdminOnlyFilter.java:71)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                at org.dspace.utils.servlet.DSpaceWebappServletFilter.doFilter(DSpaceWebappServletFilter.java:78)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
                at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
                at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
                at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [org.dspace.app.cris.model.ResearcherPage#2]
                at org.hibernate.engine.internal.StatefulPersistenceContext.checkUniqueness(StatefulPersistenceContext.java:691)
                at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performUpdate(DefaultSaveOrUpdateEventListener.java:293)
                at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsDetached(DefaultSaveOrUpdateEventListener.java:239)
                at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:109)
                at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
                at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:727)
                at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:719)
                at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:715)
                at it.cilea.osd.common.dao.impl.GenericDaoHibernateImpl.saveOrUpdate(GenericDaoHibernateImpl.java:109)
                at sun.reflect.GeneratedMethodAccessor675.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                at it.cilea.osd.common.dao.impl.NamedQueryIntroductionAdvisor$1.invoke(NamedQueryIntroductionAdvisor.java:103)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
                at com.sun.proxy.$Proxy56.saveOrUpdate(Unknown Source)
                at it.cilea.osd.common.service.PersistenceService.saveOrUpdate(PersistenceService.java:197)
                at it.cilea.osd.common.service.PersistenceService.saveOrUpdate(PersistenceService.java:173)
                at it.cilea.osd.common.service.PersistenceService$$FastClassByCGLIB$$b40d0435.invoke(<generated>)
                at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
                at org.springframework.aop.framework.Cglib2AopProxy$CglibMethodInvocation.invokeJoinpoint(Cglib2AopProxy.java:689)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
                at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:622)
                at org.dspace.app.cris.service.ApplicationService$$EnhancerByCGLIB$$825d0b14.saveOrUpdate(<generated>)
                at org.dspace.app.webui.cris.controller.admin.FormAdministrationResearcherController.onSubmit(FormAdministrationResearcherController.java:122)
                at org.springframework.web.servlet.mvc.SimpleFormController.processFormSubmission(SimpleFormController.java:272)
                at org.springframework.web.servlet.mvc.AbstractFormController.handleRequestInternal(AbstractFormController.java:268)
                at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
                at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
                ... 32 more
2017-02-07 16:32:12,330 WARN  org.dspace.app.webui.util.UIUtil @ Unable to send email alert
java.lang.NullPointerException
                at org.dspace.storage.rdbms.DatabaseManager.queryTable(DatabaseManager.java:237)
                at org.dspace.content.DSpaceObject$MetadataCache.retrieveMetadata(DSpaceObject.java:1343)
                at org.dspace.content.DSpaceObject$MetadataCache.get(DSpaceObject.java:1278)
                at org.dspace.content.DSpaceObject.getMetadata(DSpaceObject.java:686)
                at org.dspace.content.DSpaceObject.getMetadata(DSpaceObject.java:595)
                at org.dspace.content.DSpaceObject.getMetadataFirstValue(DSpaceObject.java:663)
                at org.dspace.eperson.EPerson.getFirstName(EPerson.java:775)
                at org.dspace.eperson.EPerson.getFullName(EPerson.java:751)
                at org.dspace.app.webui.util.UIUtil.sendAlert(UIUtil.java:444)
                at org.dspace.app.webui.servlet.InternalErrorServlet.doGet(InternalErrorServlet.java:54)
                at org.dspace.app.webui.servlet.InternalErrorServlet.doPost(InternalErrorServlet.java:62)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:489)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:412)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
                at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:467)
                at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:412)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:201)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
                at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
                at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
                at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Work

**Comment by lap82** [comment]
Yes this is a know issue. I try to fix for the DSpace-CRIS 5.7. Thank you.
