### ISSUE TITLE
Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]

### ISSUE THREAD

**Issue by andimalaj** [4Science/DSpace#72]
Hello,

I am trying to deploy version 5.10  from branch 5-x-x-cris ( and also for the tagged version 5.8)  . After successful build and intsall, I am trying to deploy solr and jspui web app.
Solr is deployed successfully.
But for JSPUI I get the ollowing error. I do not find the class CrisSearchService anywere in the deployment folder. How are the classes for Cris api deployed, is there any step I am missing?

`10-Apr-2019 17:45:04.625 INFORMAZIONI [http-nio-8082-exec-23] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
10-Apr-2019 17:45:06.182 GRAVE [http-nio-8082-exec-23] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener]
 java.lang.RuntimeException: Failure during filter init: Failed to startup the DSpace Service Manager: failure starting up spring service manager: Error creating bean with name 'org.dspace.servicemanager.spring.DSpaceBeanPostProcessor#0' defined in class path resource [spring/spring-dspace-applicationContext.xml]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.dspace.servicemanager.config.DSpaceConfigurationService]: : Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService
	at org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener.contextInitialized(DSpaceKernelServletContextListener.java:92)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:496)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1645)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:287)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1553)
	at org.apache.catalina.manager.ManagerServlet.deploy(ManagerServlet.java:986)
	at org.apache.catalina.manager.ManagerServlet.doGet(ManagerServlet.java:350)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.valves.RequestFilterValve.process(RequestFilterValve.java:348)
	at org.apache.catalina.valves.RemoteAddrValve.invoke(RemoteAddrValve.java:52)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to startup the DSpace Service Manager: failure starting up spring service manager: Error creating bean with name 'org.dspace.servicemanager.spring.DSpaceBeanPostProcessor#0' defined in class path resource [spring/spring-dspace-applicationContext.xml]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.dspace.servicemanager.config.DSpaceConfigurationService]: : Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService
	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:224)
	at org.dspace.servicemanager.DSpaceKernelImpl.start(DSpaceKernelImpl.java:150)
	at org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener.contextInitialized(DSpaceKernelServletContextListener.java:81)
	... 48 more
Caused by: java.lang.IllegalStateException: failure starting up spring service manager: Error creating bean with name 'org.dspace.servicemanager.spring.DSpaceBeanPostProcessor#0' defined in class path resource [spring/spring-dspace-applicationContext.xml]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.dspace.servicemanager.config.DSpaceConfigurationService]: : Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService
	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:208)
	... 50 more
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.dspace.servicemanager.spring.DSpaceBeanPostProcessor#0' defined in class path resource [spring/spring-dspace-applicationContext.xml]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.dspace.servicemanager.config.DSpaceConfigurationService]: : Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:752)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:193)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1077)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:981)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:758)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.dspace.servicemanager.spring.SpringServiceManager.startup(SpringServiceManager.java:207)
	at org.dspace.servicemanager.DSpaceServiceManager.startup(DSpaceServiceManager.java:205)
	... 50 more
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.dspace.app.cris.discovery.CrisSearchService] for bean with name 'org.dspace.discovery.SearchService' defined in file [C:\dspace_cris\config\spring\api\discovery-solr.xml]; nested exception is java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1278)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1347)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:358)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:327)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:186)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:906)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:864)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:779)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:817)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:745)
	... 63 more
Caused by: java.lang.ClassNotFoundException: org.dspace.app.cris.discovery.CrisSearchService
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:265)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:419)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1270)
	... 73 more`

May you give me aan advice please?

Thank You

**Comment by andimalaj** [comment]
The prolem seems if deployed with Netbeans. If I copy the webapp folder to tomcat manually, is OK.

**Comment by marc-brouard** [comment]
I'm getting this same error when setting this up with IntelliJ. It is working fine on my main development machine, but when I came to set it up on my laptop I am getting this error. As far as I can tell all the configuration options are the same, just the install directory is different.

**Comment by marc-brouard** [comment]
> I'm getting this same error when setting this up with IntelliJ. It is working fine on my main development machine, but when I came to set it up on my laptop I am getting this error. As far as I can tell all the configuration options are the same, just the install directory is different.

Finally figured out what was causing this error. I was deploying the wrong artifacts. It needed to be solr:war exploded and jspui:war exploded not the ones prefixed by dspace-. Hope this helps

**Comment by abollini** [comment]
thanks @marc-brouard to have shared your analysis, we were stuck as it was not reproducible
