### ISSUE TITLE
Error when running plugins

### ISSUE THREAD

**Issue by baneta** [4Science/DSpace#99]
Hello. I've even tested this on brand new installation and still getting this. I don't remember when, but it worked previously. I've checked logs and here's the result:

**2019-09-25 10:50:12,296 ERROR org.dspace.app.cris.batch.ScriptStatsMetrics @ 
java.lang.NullPointerException
	at org.dspace.app.cris.batch.ScriptStatsMetrics.main(ScriptStatsMetrics.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dspace.app.launcher.ScriptLauncher.runOneCommand(ScriptLauncher.java:226)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:78)**

I'm running this command:
**dspace dsrun org.dspace.app.cris.batch.ScriptStatsMetrics -s RPStatsAggregatorScopusIndicatorsPlugin**

**Comment by baneta** [comment]
UPDATE: Other plugins are also failing when running this:

 **dspace dsrun org.dspace.app.cris.batch.ScriptStatsMetrics -s PLUGIN_NAME_HERE**
